### PR TITLE
Deploy BinderHub on top of Kubernetes

### PR DESCRIPTION
**Pull request by zonca**
This tutorial assumes the user has a working Kubernetes deployment,
I link to my tutorial using Kubespray that is well-tested.

Is it ok if I link explicitely to https://js2.jetstream-cloud.org/?
I would like to add a screenshot of the homepage of BinderHub, how do I do that?

Please, read through it and send me feedback!

### CODE REVIEW

**Comment by zonca** [comment]
@jlf599 @jmlowe

**Comment by jlf599** [comment]
Also, I think this is good overall. I would make one suggestion of adding {target=_blank} to the end of all URLs that leave the docs site.  e.g:

`[project on GitLab](https://gitlab.com/exosphere/exosphere){target=_blank}`

**Comment by zonca** [comment]
ok @jlf599 , fixed the links and added the image. This is ready for merging.

**Comment by jlf599** [comment]
Second review complete. Approved.

**Comment by zonca** [comment]
Thanks, I see it published at https://docs.jetstream-cloud.org/general/k8sbinderhub/

**Pull request merged**
