### PR TITLE
Tutorial to deploy a Web Server with Automatic HTTPS (Caddy)

### PR DESCRIPTION
**Pull request by zonca**
Following https://github.com/jetstream-cloud/js2docs/issues/61

I have completed the technical part of the tutorial, need to write the intro.
But first wanted some feedback.

In particular the Django deployment, I like the idea of showing something more complex than static files, but maybe too complex? I can put it in a separate tutorial, or remove it from here and put it on https://www.zonca.dev/

### CODE REVIEW

**Comment by julianpistorius** [comment]
I'm on the fence about including Django, but I think on balance it is useful to include something non-trivial.

**Comment by zacharygraber** [comment]
@zonca We've moved the docs site from its current ReadTheDocs community hosting to GitLab pages, and as part of that, moved the repository to GitLab: https://gitlab.com/jetstream-cloud/docs. 

I'm getting ready to archive this (GitHub) repo and point folks toward the GitLab page instead. Would you be willing to re-open this PR in the new repo? If not, I'm happy to recreate your changes and open an MR there myself, though then the changes would live in my fork and be attributed to me. I was able to do this by:

1. Forking the repo on GitLab
2. Creating a new branch for the changes on my fork and checking it out
3. Adding the Git**Hub** repo/branch as a remote (see https://stackoverflow.com/questions/21353656/merge-git-repo-into-branch-of-another-repo)
4. Merging the commit from the Git**Hub** repo into the branch on my Git**Lab** repo
5. Opening an MR on GitLab for those changes.

-Zach

**Comment by zonca** [comment]
it is ok, I can move it over

**Comment by zonca** [comment]
moved to https://gitlab.com/jetstream-cloud/docs/-/merge_requests/86

**Pull request closed without merging**
