### PR TITLE
Deploy Kubernetes and JupyterHub with GPU support tutorial

### PR DESCRIPTION
**Pull request by zonca**
- added tutorial Kubernetes on GPU
- update title
- link from Kubernetes topic
- add target blank to links and script

### CODE REVIEW

**Comment by zonca** [comment]
@jlf599 this is ready for review, not sure if you want the script in there, but it is convenient!

@julienchastang @robertej09 @ThomasMGeo.

**Comment by zonca** [comment]
also I escaped the underscore in `{target=\_blank}.` to make `vim` happy. I hope this is not a problem for `mkdocs`.

**Comment by jlf599** [comment]
Reviewed. Looks good. Merging.

**Comment by julienchastang** [comment]
It might seem obvious, but in the `cluster.tfvars` you should also select a GPU VM, right? So instead of:

```
flavor_k8s_node = "4"
```

you should have

```
flavor_k8s_node = "10"
```

or `11`, `12`, `13` for one of the GPU VMs

```
+----+-----------+---------+------+-----------+-------+-----------+
| ID | Name      |     RAM | Disk | Ephemeral | VCPUs | Is Public |
+----+-----------+---------+------+-----------+-------+-----------+
| 10 | g3.small  |   15360 |   60 |         0 |     4 | False     |
| 11 | g3.medium |   30720 |   60 |         0 |     8 | False     |
| 12 | g3.large  |   61440 |   60 |         0 |    16 | False     |
| 13 | g3.xl     |  128000 |   60 |         0 |    32 | False     |
+----+-----------+---------+------+-----------+-------+-----------+

```

The instructions don't mention that, unless I missed it.

**Comment by zonca** [comment]
Yes
It is in cluster.tfvars itself

https://github.com/zonca/jetstream_kubespray/blob/c1c9bac4186c455e18adb5917f5af0ac9d455ce1/inventory/kubejetstream/cluster.tfvars#L42

**Comment by julienchastang** [comment]
In the end, this GPU workflow worked very well for us. Thanks again for all you help here!

**Pull request merged**
